version: '3.9'

services:
  node-api:
    image: node
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached 
    ports:
      - 4000:3000
    network_mode: host
    command: npm run dev
  mysql:
    image: mysql
    container_name: mysqldb
    ports:
      - 7000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test1234

